server:
  port: 8081  # Add this at the very top of the file

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # This is the fix for the error you see in your logs:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: midas-core-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # This tells Kafka it's safe to trust your Transaction class
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"

general:
  kafka-topic: trader-updates